AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # RDSSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: RDS Security Group
  #     SecurityGroupIngress:
  #       - CidrIp: 0.0.0.0/0
  #         IpProtocol: tcp
  #         FromPort: 3306
  #         ToPort: 3306

  # RDSInstance:
  #   Type: AWS::RDS::DBInstance
  #   Properties:
  #     AllocatedStorage: 20
  #     DBInstanceIdentifier: mysql-rds
  #     Engine: mysql
  #     EngineVersion: "5.7"
  #     DBInstanceClass: db.t2.micro
  #     PubliclyAccessible: true
  #     VPCSecurityGroups:
  #       - Fn::GetAtt: RDSSecurityGroup.GroupId
  #     MasterUsername: admin
  #     MasterUserPassword: password
  #     BackupRetentionPeriod: 0
  #     StorageType: gp2

  DBHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::ServiceCatalog::ProductName}/db-host"
      Type: String
      Value: "todo"

  DBPort:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::ServiceCatalog::ProductName}/db-port"
      Type: String
      Value: "3306"

  DBUser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::ServiceCatalog::ProductName}/db-user"
      Type: String
      Value: "admin"

  DBPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::ServiceCatalog::ProductName}/db-pass"
      Type: String
      Value: "password"

# Outputs:
#   RDSEndpoint:
#     Description: RDS Endpoint
#     Value: !GetAtt RDSInstance.Endpoint.Address
#     Export:
#       Name: RDSEndpoint
#   RDSPort:
#     Description: RDS Port
#     Value: !GetAtt RDSInstance.Endpoint.Port
#     Export:
#       Name: RDSPort
