AWSTemplateFormatVersion: "2010-09-09"

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBInstanceIdentifier: mysql-rds
      Engine: mysql
      EngineVersion: "5.7"
      DBInstanceClass: db.t2.micro
      PubliclyAccessible: true
      VPCSecurityGroups:
        - Fn::GetAtt: RDSSecurityGroup.GroupId
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      BackupRetentionPeriod: 0
      StorageType: gp2

  DBHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/stack/db-host"
      Type: String
      Value: !GetAtt RDSInstance.Endpoint.Address

  DBPort:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/stack/db-port"
      Type: String
      Value: "3306"

  DBUser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/stack/db-user"
      Type: String
      Value: "admin"

  DBPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/stack/db-pass"
      Type: String
      Value: "password"
