AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  InputDBName:
    Default: unknown_db
    Description: The MySql Database name
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "^[a-z]+(_[a-z]+)*$"
    ConstraintDescription: Must be snake case.

# todo add no echo
  InputDBUser:
    Default: "unset"
    Description: The database admin account username
    Type: String
    MinLength: "3"
    MaxLength: "16"
    AllowedPattern: "^[a-z]+(_[a-z]+)*$"
    ConstraintDescription: Must be snake case.

  InputDBPassword:
    Default: "unset"
    Description: The database admin account password
    Type: String
    MinLength: "3"
    MaxLength: "32"
    AllowedPattern: "^[a-zA-Z0-9]+$"
    ConstraintDescription: Must be alphanumeric.
    # todo allow special characters too

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBInstanceIdentifier: mysql-rds
      Engine: mysql
      EngineVersion: "5.7"
      DBInstanceClass: db.t2.micro
      PubliclyAccessible: true
      VPCSecurityGroups:
        - Fn::GetAtt: RDSSecurityGroup.GroupId
      MasterUsername: !Ref InputDBUser
      MasterUserPassword: !Ref InputDBPassword
      BackupRetentionPeriod: 0
      StorageType: gp2

  DBHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /stack/db-host
      Type: String
      Value: !GetAtt RDSInstance.Endpoint.Address

  DBPort:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /stack/db-port
      Type: String
      Value: "3306"

  DBUser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /stack/db-user
      Type: String
      Value: !Ref InputDBUser

  DBPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /stack/db-pass
      Type: String
      Value: !Ref InputDBPassword
# todo output the db host
